// sales order listing payload
export const body = {
  data: {
    _domain: "self.template = false and self.statusSelect > 2",
    _domainContext: {
      status: "3",
      _id: null,
      _internalUser: 1,
      _myActiveTeam: {
        code: "GRL",
        id: 4,
        name: "General",
      },
      _template: false,
    },
  },
  fields: [
    "amountInvoiced",
    "clientPartner.fullName",
    "company",
    "currency.symbol",
    "deliveryState",
    "exTaxTotal",
    "externalReference",
    "inTaxTotal",
    "orderBeingEdited",
    "orderDate",
    "saleOrderSeq",
    "statusSelect",
    "stockLocation",
    "tradingName",
  ],
  limit: 40,
  offset: 0,
  sortBy: ["-orderDate"],
};

export const fetchBody = {
  fields: [
    "carrierPartner",
    "expectedRealisationDate",
    "periodicityTypeSelect",
    "mainInvoicingAddressStr",
    "deliveryCondition",
    "deliveryAddress",
    "nextInvoicingEndPeriodDate",
    "opportunity",
    "attrs",
    "externalReference",
    "clientPartner.saleOrderInformation",
    "currentContractPeriodEndDate",
    "confirmationDateTime",
    "saleOrderSeq",
    "stockLocation",
    "computationDate",
    "advancePaymentList",
    "createdByInterco",
    "numberOfPeriods",
    "proformaComments",
    "contractPeriodInMonths",
    "company.currency",
    "timetableList",
    "cancelReasonStr",
    "isIspmRequired",
    "currency",
    "contactPartner",
    "deliveryDate",
    "cancelReason",
    "tradingName",
    "totalCostPrice",
    "toInvoiceViaTask",
    "blockedOnCustCreditExceed",
    "subscriptionComment",
    "hideDiscount",
    "team",
    "statusSelect",
    "companyBankDetails",
    "standardDelay",
    "specificNotes",
    "manualUnblock",
    "pickingOrderComments",
    "internalNote",
    "saleOrderLineTaxList",
    "orderNumber",
    "isNeedingConformityCertificate",
    "taxTotal",
    "advanceTotal",
    "project",
    "totalGrossMargin",
    "noticePeriodInDays",
    "productionNote",
    "invoiceComments",
    "freightCarrierMode",
    "isTacitAgreement",
    "inTaxTotal",
    "orderBeingEdited",
    "markup",
    "contractStartDate",
    "subscriptionText",
    "nextInvoicingDate",
    "creationDate",
    "advancePaymentAmountNeeded",
    "mainInvoicingAddress",
    "saleOrderLineList",
    "clientPartner",
    "saleOrderTypeSelect",
    "incoterm",
    "orderDate",
    "endOfValidityDate",
    "timetableTemplate",
    "amountToBeSpreadOverTheTimetable",
    "currency.symbol",
    "description",
    "forwarderPartner",
    "inAti",
    "priceList",
    "duration",
    "marginRate",
    "printingSettings",
    "directOrderLocation",
    "company",
    "deliveryAddressStr",
    "shipmentDate",
    "nextInvoicingStartPeriodDate",
    "accountedRevenue",
    "specificPackage",
    "paymentMode",
    "paymentCondition",
    "contractEndDate",
    "exTaxTotal",
    "shipmentMode",
    "salespersonUser",
    "versionNumber",
    "amountInvoiced",
    "confirmedByUser",
    "advancePaymentNeeded",
    "deliveryState",
    "interco",
    "deliveryComments",
  ],
  related: {},
};
